include:
  - project: bazel_rules_hdl-ci-scripts
    file: bazel_rules_hdl.yml

stages:
  - prepare
  - test
  - lint

# Dependencies
.install_deps: &install_deps |-
  apt-get -qqy update
  apt-get -qqy --no-install-recommends install ca-certificates build-essential golang-go python3 python3-dev python3-pip python3-venv wget

# Download bazelisk and create a link called 'bazel'.
.install_bazelisk: &install_bazelisk |-
  go install github.com/bazelbuild/bazelisk@latest
  ln -s $(go env GOPATH)/bin/bazelisk /usr/local/bin/bazel
  export PATH=$PATH:$(go env GOPATH)/bin
  export PATH=$PATH:/usr/local/bin

# Run Verilator rules
test_verilator:
  image: debian:12
  stage: test
  script:
    - *install_deps
    - *install_bazelisk
    - bazel build //verilator/tests:all
    - bazel test //verilator/tests:all

# Run Verilog rules
test_verilog:
  image: debian:12
  stage: test
  script:
    - *install_deps
    - *install_bazelisk
    - bazel build //verilog/tests:top_filelist_test

# Runs //vcs/tests:* rules
test_vcs:
  extends: .vcs_templ

# Runs //dc/tests:* rules
test_dc:
  extends: .dc_templ

test_vc_static:
  extends: .vc_static_templ

# Should be aligned with .github/workflows/lint.yml
buildifier:
  image: debian:12
  stage: lint
  variables:
    BUILDIFIER_VERSION: v6.3.3
  dependencies: []
  script:
    - *install_deps
    - wget https://github.com/bazelbuild/buildtools/releases/download/${BUILDIFIER_VERSION}/buildifier-linux-amd64 -O /usr/local/bin/buildifier
    - chmod +x /usr/local/bin/buildifier
    - buildifier -lint=warn -mode=check -warnings=all -r .
